version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/conf.py

formats: all

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - '"cython<3.0.0" && pip install --no-build-isolation pyyaml==6.0'
    - requirements: docs/requirements.tx
